name: first-workflow
on: [workflow_dispatch]
jobs:

  test-second-job:
    runs-on: windows-latest
    steps:
      - name: second job step
        run: |
          echo "execution completed!"
          echo "Thank You!!"
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: first-artifact
      - name: Display artifact content
        run: |
          echo "Content of the artifact:"
          cat artifact.txt
          echo "Artifact content displayed successfully."

  test-first-job:
    runs-on: ubuntu-latest
    steps:
    - name: test step
      run: echo "Hi. This is the first step" >> artifact.txt
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: first-artifact
        path: ./artifact.txt
  
  
    
    
