name: first-workflow
on: [workflow_dispatch]
jobs:
  test-first-job:
    runs-on: ubuntu-latest
    steps:
    - name: test step
      run: echo "Hi. This is the first step"
  
  test-second-job:
    runs-on: windows-latest
    steps:
      - name: second job step
        run: |
          echo "execution completed!"
          echo "Thank You!!"
  
    
