name: Issues
on: 
  issues:
    types: [opened, edited, reopened, closed]
jobs:
  issue-job:
    runs-on: ubuntu-latest
    steps:
      - name: Issue Details
        run: |
          echo "${{ toJson(github.event.issue) }}"

