name: Test & Deploy
on: [push, workflow_dispatch]
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get completed
        uses: actions/checkout@v2
      - name: Execute Lint
        run: |
          echo "Linting the code..."
          npm lint
          echo "Linting completed successfully."
