name: Test & Deploy
on: [push, workflow_dispatch]
jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get completed
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          npm install
          echo "Dependencies installed successfully."
      - name: Execute Lint
        run: |
          echo "Linting the code..."
          npm run lint
          echo "Linting completed successfully."
  
  test-job:
    needs: lint-job
    runs-on: ubuntu-latest
    steps:
      - name: Get completed
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          npm install
          echo "Dependencies installed successfully."
      - name: Run Tests
        run: |
          echo "Running tests..."
          npm run test
          echo "Tests completed successfully."
  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - name: Get completed
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          npm install
          echo "Dependencies installed successfully."
      - name: Deploy Application
        run: |
          echo "Deploying application..."
          npm run deploy
          echo "Deployment completed successfully."